# Generated by Django 6.0.2 on 2026-02-19 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0007_training_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, help_text='Main text for the lesson')),
                ('video_url', models.URLField(blank=True, help_text='Paste a YouTube or Vimeo link', null=True)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='training_files/')),
                ('order', models.IntegerField(default=1)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='gameplay.training')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
