# Generated by Django 6.0.2 on 2026-02-20 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0008_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, help_text='What does this team do?'),
        ),
        migrations.AddField(
            model_name='department',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube intro video', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gameplay.department'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.department'),
        ),
        migrations.AlterField(
            model_name='question',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gameplay.training'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.training'),
        ),
    ]
